# Generated by Django 5.2.1 on 2026-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('region', models.CharField(max_length=10)),
                ('mmr', models.FloatField(default=1500)),
                ('peak_mmr', models.FloatField(default=1500)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('peak_streak', models.IntegerField(default=0)),
                ('role_preference', models.CharField(choices=[('tank', 'Tank'), ('dps', 'DPS'), ('sup', 'Support'), ('dps_tank', 'DPS / Tank'), ('tank_sup', 'Tank / Support'), ('dps_sup', 'DPS / Support'), ('flex', 'Flex')], default='flex', max_length=20)),
                ('mvps', models.PositiveIntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
                ('last_match_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
