# Generated by Django 5.2.1 on 2026-06-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], max_length=20, null=True)),
                ('team_1_mmr', models.FloatField()),
                ('team_2_mmr', models.FloatField()),
                ('mmr_difference', models.FloatField()),
                ('role_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], max_length=20)),
                ('assigned_role', models.CharField(choices=[('tank', 'Tank'), ('dps', 'DPS'), ('sup', 'Support')], max_length=20)),
                ('mmr_before', models.FloatField()),
                ('mmr_after', models.FloatField(blank=True, null=True)),
                ('mmr_change', models.FloatField(default=0)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='players.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='matches.MatchPlayer', to='players.player'),
        ),
    ]
