# Generated by Django 5.2.1 on 2026-06-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='map_name',
            field=models.CharField(blank=True, choices=[('ascension_peak', 'Ascension Peak'), ('bazaar', 'Bazaar'), ('brightmarsh', 'Brightmarsh'), ('frog_isle', 'Frog Isle'), ('frozen_guard', 'Frozen Guard'), ('ice_mines', 'Ice Mines'), ('jaguar_falls', 'Jaguar Falls'), ('serpent_beach', 'Serpent Beach'), ('shattered_desert', 'Shattered Desert'), ('splitstone_quarry', 'Splitstone Quarry'), ('stone_keep', 'Stone Keep'), ('timber_mill', 'Timber Mill'), ('warders_gate', "Warder's Gate")], default='', max_length=50),
        ),
    ]
