# Generated by Django 5.2.1 on 2026-06-05 19:05

from django.db import migrations, models


ACTIVE_MAP_KEYS = [
    "ascension_peak",
    "bazaar",
    "brightmarsh",
    "frog_isle",
    "frozen_guard",
    "fish_market",
    "ice_mines",
    "jaguar_falls",
    "serpent_beach",
    "shattered_desert",
    "splitstone_quarry",
    "stone_keep",
    "timber_mill",
    "warders_gate",
    "dawnforge",
]


def seed_active_maps(apps, schema_editor):
    ActiveMap = apps.get_model("matches", "ActiveMap")

    for map_key in ACTIVE_MAP_KEYS:
        ActiveMap.objects.get_or_create(map_name=map_key)


def unseed_active_maps(apps, schema_editor):
    ActiveMap = apps.get_model("matches", "ActiveMap")
    ActiveMap.objects.filter(map_name__in=ACTIVE_MAP_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_map_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(choices=[('ascension_peak', 'Ascension Peak'), ('bazaar', 'Bazaar'), ('brightmarsh', 'Brightmarsh'), ('frog_isle', 'Frog Isle'), ('frozen_guard', 'Frozen Guard'), ('fish_market', 'Fish Market'), ('ice_mines', 'Ice Mines'), ('jaguar_falls', 'Jaguar Falls'), ('serpent_beach', 'Serpent Beach'), ('shattered_desert', 'Shattered Desert'), ('splitstone_quarry', 'Splitstone Quarry'), ('stone_keep', 'Stone Keep'), ('timber_mill', 'Timber Mill'), ('warders_gate', "Warder's Gate"), ('dawnforge', 'Dawnforge')], max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('map_name',),
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='map_name',
            field=models.CharField(blank=True, choices=[('ascension_peak', 'Ascension Peak'), ('bazaar', 'Bazaar'), ('brightmarsh', 'Brightmarsh'), ('frog_isle', 'Frog Isle'), ('frozen_guard', 'Frozen Guard'), ('fish_market', 'Fish Market'), ('ice_mines', 'Ice Mines'), ('jaguar_falls', 'Jaguar Falls'), ('serpent_beach', 'Serpent Beach'), ('shattered_desert', 'Shattered Desert'), ('splitstone_quarry', 'Splitstone Quarry'), ('stone_keep', 'Stone Keep'), ('timber_mill', 'Timber Mill'), ('warders_gate', "Warder's Gate"), ('dawnforge', 'Dawnforge')], default='', max_length=50),
        ),
        migrations.RunPython(seed_active_maps, unseed_active_maps),
    ]
