# Generated by Django 5.2.1 on 2026-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_activemap_alter_match_map_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_min_rating', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'rating settings',
            },
        ),
    ]
